solution
DS-83/skills pull request #1
Opened 2022-11-20 13:42 UTC by DS-83

2022-11-20 14:36 UTC, spiridonovaalexis requested changes

2022-11-20 14:36 UTC, spiridonovaalexis commented on conveyor/conveyor.go
> +	for i := 0; i < len(tasksFlow); i++ {
Можно не создавать сразу массив каналов, а создать один, а далее создавать другие каналы уже в цикле

2022-11-20 14:36 UTC, spiridonovaalexis commented on conveyor/conveyor.go
> +	wg.Add(len(tasksFlow))
Добавлять в waitgroup наверное все-таки стоит в цикле непосредственно перед вызовом горутины

2022-11-20 14:36 UTC, spiridonovaalexis commented on linksSearcher/linksSearcher.go
>  	// implement here
Это коммент уже убирай, реализовал же😅

2022-11-20 14:36 UTC, spiridonovaalexis commented on linksSearcher/linksSearcher.go
> +	r := regexp.MustCompile(regexpStr)
Лучше скомпилировать регулярку один раз и вынести в константу, и потом просто матчить
`var regURL = regexp.MustCompile(...)`

2022-11-20 14:36 UTC, spiridonovaalexis commented on linksSearcher/linksSearcher.go
> +		if resp.StatusCode == 200 {
`http.StatusOK`

2022-11-20 14:36 UTC, spiridonovaalexis commented on linksSearcher/linksSearcher.go
> +	urls := cutString(s)
`urls := regURL.FindAllString(s, -1)`
Можно использовать вот такой метод скомпилированной регулярки

2022-11-20 14:36 UTC, spiridonovaalexis commented on linksSearcher/linksSearcher.go
> +		if wg.count == procNumber {
Давай используем примитив синхронизации вместо этого?

2022-11-20 14:36 UTC, spiridonovaalexis commented on linksSearcher/linksSearcher.go
> +		resp, err := http.Get(url)
А если запрос не будет отвечать? Давай от этого тоже сделаем защиту

2022-11-23 09:13 UTC, DS-83 commented on conveyor/conveyor.go
> +	for i := 0; i < len(tasksFlow); i++ {
done

2022-11-23 09:13 UTC, DS-83 commented on conveyor/conveyor.go
> +	wg.Add(len(tasksFlow))
done

2022-11-23 09:17 UTC, DS-83 commented on linksSearcher/linksSearcher.go
>  	// implement here
done

2022-11-23 09:19 UTC, DS-83 commented on linksSearcher/linksSearcher.go
> +	r := regexp.MustCompile(regexpStr)
done

2022-11-23 09:20 UTC, DS-83 commented on linksSearcher/linksSearcher.go
> +		if resp.StatusCode == 200 {
done

2022-11-23 11:17 UTC, DS-83 commented on linksSearcher/linksSearcher.go
> +	urls := cutString(s)
Пробовал. Результат не соотвествует ожиданиям:
https://www.digitalocean.com/community/tutorials
https://www.digitalocean.com/community/tutorials
mlhttps://ru.wikipedia.org
lpmhttps://stackoverflow.com/questions
Видимо что-то с регулярным выражением, но я не знаю как исправить :)

2022-11-24 13:14 UTC, DS-83 commented on linksSearcher/linksSearcher.go
> +		resp, err := http.Get(url)
timeout := time.After(5 * time.Second)
	for i := 0; i < len(urls); i++ {
		select {
		case result := <-ch:
			res = append(res, result)
		case <-timeout:
			return
		}
	}

2022-11-30 08:22 UTC, spiridonovaalexis commented on linksSearcher/linksSearcher.go
> +		if wg.count == procNumber {
C wait group counter, на мой взгляд, как-то сложно получилось
Посмотри в сторону worker pool концепции
В качестве примитива синхронизации можно использовать каналы

2022-11-30 08:22 UTC, spiridonovaalexis commented on linksSearcher/linksSearcher.go
> +	r := regexp.MustCompile(regexpStr)
Лучше вынести в константу вместо regexpStr, чтобы компилировалась один раз при запуске приложения регулярка, а так она каждый раз компилируется

2022-11-30 08:22 UTC, spiridonovaalexis commented on linksSearcher/linksSearcher.go
> +	urls := cutString(s)
Вместо [A-Za-z]{3,9} можно, например, сделать https, чтобы только https ссылки матчились, а то так он сматчит любые буквы до :

2022-12-01 09:25 UTC, merged